config/routes.rb
Rails.application.routes.draw do

  get 'post/create'

  root 'home#top'
	get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
	resources :policies, only: :index

	resources :users, except: [:new, :create] do
		collection do
			get :departments_select
		end
	end
  resources :topic
  resources :posts

	namespace :admin do
		resources :users, :except => [:show]
		resources :faculties
		resources :departments
    resources :circles
    resources :topics
  end

end

app/models/circle.rb
class Circle < ActiveRecord::Base

  has_many :user_circles
  has_many :user, through: :user_circles

  validates :name, :category, presence: true
  validates :name, uniqueness: true
  enum category: { sport: 0, culture: 1, other: 2 }
end

app/controllers/admin/circles_controller.rb
class Admin::CirclesController < AdminController
  before_action :set_circle, only: [:show, :edit, :update, :destroy]

  # GET /admin/circles
  # GET /admin/circles.json
  def index
    @circles = Circle.all
  end

  # GET /admin/circles/1
  # GET /admin/circles/1.json
  def show
  end

  # GET /admin/circles/new
  def new
    @circle = Circle.new
  end

  # GET /admin/circles/1/edit
  def edit
  end

  # POST /admin/circles
  # POST /admin/circles.json
  def create
    @circle = Circle.new(circle_params)

    respond_to do |format|
      if @circle.save
        format.html { redirect_to admin_circles_path, notice: 'Circle was successfully created.' }
        format.json { render :show, status: :created, location: @circle }
      else
        format.html { render :new }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/circles/1
  # PATCH/PUT /admin/circles/1.json
  def update
    respond_to do |format|
      if @circle.update(circle_params)
        format.html { redirect_to admin_circles_path, notice: 'Circle was successfully updated.' }
        format.json { render :show, status: :ok, location: @circle }
      else
        format.html { render :edit }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/circles/1
  # DELETE /admin/circles/1.json
  def destroy
    @circle.destroy
    respond_to do |format|
      format.html { redirect_to admin_circles_url, notice: 'Circle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circle
      @circle = Circle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circle_params
      params.require(:circle).permit(:name, :category)
    end
end

app/views/admin/circles/_form.html.erb
<%= form_for @circle, :url => { :controller => "admin/circles", :action => :create } do |f| %>
  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circle.errors.count, "error") %> prohibited this admin_circle from being saved:</h2>

      <ul>
      <% @circle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-xs-6">
      <label>サークル名</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group col-xs-6">
      <label>サークルカテゴリー</label>
      <%= f.select :category, Circle.categories.keys.to_a, {}, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6">
      <%= f.submit "作成", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/circles/_form_update.html.erb
<%= form_for @circle, :url => { :controller => "admin/circles", :action => :update } do |f| %>
  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circle.errors.count, "error") %> prohibited this admin_circle from being saved:</h2>

      <ul>
      <% @circle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-xs-6">
      <label>サークル名</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group col-xs-6">
      <label>サークルカテゴリー</label>
      <%= f.select :category, Circle.categories.keys.to_a, {}, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6">
      <%= f.submit "アップデート", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-6">
    <%= link_to 'Destroy', admin_circle_path(@circle), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/circles/edit.html.erb
<style>
  * {
    color: black;
  }
</style>
<h1>サークル編集</h1>

<%= render 'form_update' %>

<%= link_to 'Back', admin_circles_path %>

app/views/admin/circles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>サークル一覧</h1>

<table class="table table-striped Admin__table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @circles.each do |circle| %>
      <tr>
        <td>
          <%= circle.name %>
        </td>
        <td>
          <%= circle.category %>
        </td>
        <td><%= link_to 'Edit', edit_admin_circle_path(circle), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Circle', new_admin_circle_path %>

app/views/admin/circles/new.html.erb
<h1>サークル新規作成</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_circles_path %>