config/routes.rb
Rails.application.routes.draw do

  get 'post/create'

  root 'home#top'
	get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
	resources :policies, only: :index

	resources :users, except: [:new, :create] do
		collection do
			get :departments_select
		end
	end
  resources :topic
  resources :posts

	namespace :admin do
		resources :users, :except => [:show]
		resources :faculties
		resources :departments
    resources :circles
    resources :topics
  end

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :faculty
  validates :department_name, presence: true
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < AdminController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /admin/departments
  # GET /admin/departments.json
  def index
    @departments = Department.all
  end

  # GET /admin/departments/1
  # GET /admin/departments/1.json
  def show
  end

  # GET /admin/departments/new
  def new
    @department = Department.new
  end

  # GET /admin/departments/1/edit
  def edit
  end

  # POST /admin/departments
  # POST /admin/departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to admin_departments_path, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/departments/1
  # PATCH/PUT /admin/departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to admin_departments_path, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/departments/1
  # DELETE /admin/departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to admin_departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:department_name, :faculty_id)
    end
end

app/views/admin/departments/_form.html.erb
<%= form_for @department, :url => { :controller => "admin/departments", :action => :create } do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this admin_department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.collection_select(
          :faculty_id,
          Faculty.all,
          :id,
          :faculty_name,
          { include_blank: "Please select one" },
          { class: "form-control" }
    ) %>
  </div>

  <div class="form-group">
    <label>学科名</label>
    <%= f.text_field :department_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/departments/_form_update.html.erb
<%= form_for @department, :url => { :controller => "admin/departments", :action => :update } do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this admin_department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.collection_select(
          :faculty_id,
          Faculty.all,
          :id,
          :faculty_name,
          { include_blank: "Please select one" },
          { class: "form-control" }
    ) %>
  </div>

  <div class="form-group">
    <label>学部名</label>
    <%= f.text_field :department_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<td><%= link_to 'Destroy', admin_department_path(@department), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>

app/views/admin/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form_update' %>

<%= link_to 'Back', admin_departments_path %>

app/views/admin/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departments</h1>

<table class="table table-striped Admin__table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td>
          <%= department.department_name %>
        </td>
        <td><%= link_to 'Edit', edit_admin_department_path(department), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_admin_department_path %>

app/views/admin/departments/new.html.erb
<h1>New Admin Faculty</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_departments_path %>

app/views/admin/departments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_faculty_path(@admin_faculty) %> |
<%= link_to 'Back', admin_faculties_path %>