config/routes.rb
Rails.application.routes.draw do

  get 'post/create'

  root 'home#top'
	get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
	resources :policies, only: :index

	resources :users, except: [:new, :create] do
		collection do
			get :departments_select
		end
	end
  resources :topic
  resources :posts

	namespace :admin do
		resources :users, :except => [:show]
		resources :faculties
		resources :departments
    resources :circles
    resources :topics
  end

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  validates :faculty_name, presence: true
  has_many :department
end

app/controllers/admin/faculties_controller.rb
class Admin::FacultiesController < AdminController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /admin/faculties
  # GET /admin/faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /admin/faculties/1
  # GET /admin/faculties/1.json
  def show
  end

  # GET /admin/faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /admin/faculties/1/edit
  def edit
  end

  # POST /admin/faculties
  # POST /admin/faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to admin_faculties_path, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/faculties/1
  # PATCH/PUT /admin/faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to admin_faculties_path, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/faculties/1
  # DELETE /admin/faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to admin_faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:faculty_name)
    end
end

app/helpers/admin/faculties_helper.rb
module Admin::FacultiesHelper
end

app/views/admin/faculties/_form.html.erb
<%= form_for @faculty, :url => { :controller => "admin/faculties", :action => :create } do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this admin_faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>学部名</label>
    <%= f.text_field :faculty_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/faculties/_form_update.html.erb
<%= form_for @faculty, :url => { :controller => "admin/faculties", :action => :update } do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this admin_faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>学部名</label>
    <%= f.text_field :faculty_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<td><%= link_to 'Destroy', admin_faculty_path(@faculty), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>

app/views/admin/faculties/edit.html.erb
<h1>Editing Admin Faculty</h1>

<%= render 'form_update' %>

<%= link_to 'Back', admin_faculties_path %>

app/views/admin/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>学部一覧</h1>

<table class="table table-striped Admin__table">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td>
          <%= faculty.faculty_name %>
        </td>
        <td><%= link_to 'Edit', edit_admin_faculty_path(faculty), class: "btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_admin_faculty_path %>

app/views/admin/faculties/new.html.erb
<h1>New Admin Faculty</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_faculties_path %>

app/views/admin/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_faculty_path(@admin_faculty) %> |
<%= link_to 'Back', admin_faculties_path %>