config/routes.rb
Rails.application.routes.draw do

  get 'post/create'

  root 'home#top'
	get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
	resources :policies, only: :index

	resources :users, except: [:new, :create] do
		collection do
			get :departments_select
		end
	end
  resources :topic
  resources :posts

	namespace :admin do
		resources :users, :except => [:show]
		resources :faculties
		resources :departments
    resources :circles
    resources :topics
  end

end

app/views/shared/_menu.html.erb
<div class="User__new-button">
  <p class="Button Button__menu">
    MENU
  </p>
</div>
<div class="Menu">
  <div class="User__new-button">
    <p class="Button Button__menu">
      CLOSE
    </p>
  </div>
  <ul class="Menu__list">
    <li><i class="fa fa-2x fa-home" aria-hidden="true"></i><%= link_to "HOME", users_path, class: "Menu__item" %></li>
    <li><i class="fa fa-2x fa-user" aria-hidden="true"></i><%= link_to 'プロフィール', edit_user_path(current_user), class: "Menu__item" %></li>
    <li><i class="fa fa-2x fa-comments-o" aria-hidden="true"></i><%= link_to "掲示板一覧", topic_index_path, class: "Menu__item" %></li>
    <% if current_user.department_id.present? %>
      <% department = Department.find( current_user.department_id ).department_name %>
      <li><i class="fa fa-2x fa-coffee" aria-hidden="true"></i><%= link_to "#{department}の掲示板", topic_path( Topic.where(belong_type: "department", belong_id: current_user.department_id ).first ), class: "Menu__item" %></li>
    <% end %>
  </ul>

</div>